/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderConfig = IDL.Record({
  'base' : IDL.Text,
  'core' : IDL.Text,
  'finish' : IDL.Text,
  'crunch' : IDL.Text,
  'infusion' : IDL.Text,
});
export const OrderId = IDL.Text;
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'createdAt' : Timestamp,
  'config' : OrderConfig,
  'totalPrice' : IDL.Nat,
});
export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addOrder' : IDL.Func(
      [OrderConfig, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderConfig = IDL.Record({
    'base' : IDL.Text,
    'core' : IDL.Text,
    'finish' : IDL.Text,
    'crunch' : IDL.Text,
    'infusion' : IDL.Text,
  });
  const OrderId = IDL.Text;
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'createdAt' : Timestamp,
    'config' : OrderConfig,
    'totalPrice' : IDL.Nat,
  });
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addOrder' : IDL.Func(
        [OrderConfig, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };