/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : OrderId,
  'createdAt' : Timestamp,
  'config' : OrderConfig,
  'totalPrice' : bigint,
}
export interface OrderConfig {
  'base' : string,
  'core' : string,
  'finish' : string,
  'crunch' : string,
  'infusion' : string,
}
export type OrderId = string;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'price' : bigint,
}
export type ProductId = string;
export type Timestamp = bigint;
export interface _SERVICE {
  'addOrder' : ActorMethod<
    [OrderConfig, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];